# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tldw < Formula
  desc "Too Long; Didn't Watch - YouTube video summarizer (CLI + MCP)"
  homepage "https://github.com/rtzll/tldw"
  version "0.16.1"

  depends_on "ffmpeg"
  depends_on "yt-dlp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rtzll/tldw/releases/download/v0.16.1/tldw_0.16.1_darwin_amd64.tar.gz"
      sha256 "5e60b04ebe14ed213eb705eb0670819859a80ae19806f203ad4411cffce9fc06"

      define_method(:install) do
        bin.install "tldw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rtzll/tldw/releases/download/v0.16.1/tldw_0.16.1_darwin_arm64.tar.gz"
      sha256 "b9a7afc813c5bcb469cc88d13c7a46f378bd1872a33631de7315d26cf83a80f0"

      define_method(:install) do
        bin.install "tldw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtzll/tldw/releases/download/v0.16.1/tldw_0.16.1_linux_amd64.tar.gz"
      sha256 "ab8b21e743198dbaa95e4bb14c0f3760ffb4cc9160728900041028d842fa6acf"
      define_method(:install) do
        bin.install "tldw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtzll/tldw/releases/download/v0.16.1/tldw_0.16.1_linux_arm64.tar.gz"
      sha256 "1ba69372c2256111296bb136edd694a86969338894091c3742a7439d81da65e4"
      define_method(:install) do
        bin.install "tldw"
      end
    end
  end

  test do
    system "#{bin}/tldw", "version"
  end
end
