# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tldw < Formula
  desc "Too Long; Didn't Watch - YouTube video summarizer (CLI + MCP)"
  homepage "https://github.com/rtzll/tldw"
  version "0.12.0"

  depends_on "ffmpeg"
  depends_on "yt-dlp"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rtzll/tldw/releases/download/v0.12.0/tldw_0.12.0_darwin_amd64.tar.gz"
      sha256 "b5ca72a07917228a13542f5d5241e8638f7034566dc3eeb7ba2c8c15455809a8"

      def install
        bin.install "tldw"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rtzll/tldw/releases/download/v0.12.0/tldw_0.12.0_darwin_arm64.tar.gz"
      sha256 "a2737d03307189f002e028fb64da9de1db4d64b0a3cbe2ce198460b521a5265b"

      def install
        bin.install "tldw"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtzll/tldw/releases/download/v0.12.0/tldw_0.12.0_linux_amd64.tar.gz"
      sha256 "488fb42f08c55a3543cd053cc34030e02406f89973ba7c0fc52fe0e62fd7106b"
      def install
        bin.install "tldw"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rtzll/tldw/releases/download/v0.12.0/tldw_0.12.0_linux_arm64.tar.gz"
      sha256 "1458b31f4d17d9d74273076b04dc774a92e5597e3ec87d3f05a2ad6d1ea95b02"
      def install
        bin.install "tldw"
      end
    end
  end

  test do
    system "#{bin}/tldw", "version"
  end
end
